blog/urls.py
from django.urls import path
from blog.views import all_posts , single_post , new_post , PostList
#have to import functions to declare 

app_name='blog'

urlpatterns = [
    path('' , all_posts , name='blog_list'),
    path('<int:id>',single_post, name='blog_detail'),
    path('new' , new_post , name='new_post'), #new is a name of html page



    #CBV
    path('cbv',PostList.as_view(), name='all_post_cbv'),
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/' , include('blog.urls' ,namespace='blog'))
]

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
post_type = [
    ('draft' ,'draft'),
    ('published' , 'published')
]

class Post(models.Model): #db table
    title = models.CharField(max_length=50 , unique=True) #db colomn
    content = models.TextField(max_length=2000 , null=True , blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default = False)
    author_mail = models.EmailField(default='')
    typee = models.CharField(choices=post_type ,default='draft', max_length=20 )
    image = models.ImageField(upload_to = 'post/' )


    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:       #to define form
        model = Post
     #   fields = '__all__' 

     #  fields = ['content','image'] #to show specific fields

        exclude = ['created_at',]   #to show all except one field
       

blog/views.py
from django.shortcuts import render,redirect,reverse
from .models import Post
from .forms import PostForm
from django.views.generic import ListView , DetailView
# Create your views here.



class PostList(ListView):
    model = Post
    template_name = 'blog_list.html'



#show all posts
def all_posts(request):
    all_posts =Post.objects.all()
   
    return render(request , 'post/all_posts.html' ,{'posts':all_posts} )

#show single post
def single_post(request,id):
    single_post = Post.objects.get(id=id)
    return render(request , 'post/single_post.html' ,{'post':single_post} )

#add post
def new_post(request):
  #  print('nnn') # to test data
    if request.method=='POST':
        form = PostForm(request.POST , request.FILES) #Request.files to recieve data (audio, imgs, videos)
        if form.is_valid():
           form.save()
           return redirect(reverse('blog:blog_list'))
    else:
        form = PostForm()
    return render(request, 'post/new.html' , {'form':form})

blog/templates/blog_list.html
<!--links called by namespace from main url then by name from sub url-->

<h1><a href="{% url 'blog:blog_list' %}">Welcom to our blog</a></h1>

<h3><a href="{% url 'blog:new_post'%}">Add new post</a></h3>
<hr>
<!--<p>{{posts}}</p>-->
<!--or-->
{% for x in object_list %}
   <!--have to call the namespace of the app from main url : name of sub url then take an id -->
   <h3><a href="{% url 'blog:blog_detail' x.id %}">{{x}}</a></h3>
{% endfor %}

blog/templates/post/all_posts.html
<!--links called by namespace from main url then by name from sub url-->

<h1><a href="{% url 'blog:blog_list' %}">Welcom to our blog</a></h1>

<h3><a href="{% url 'blog:new_post'%}">Add new post</a></h3>
<hr>
<!--<p>{{posts}}</p>-->
<!--or-->
{% for x in posts %}
   <!--have to call the namespace of the app from main url : name of sub url then take an id -->
   <h3><a href="{% url 'blog:blog_detail' x.id %}">{{x}}</a></h3>
{% endfor %}

blog/templates/post/new.html
<h3>Add new post</h3>

<!--it has to a form tag to send data to a server cause django cannot recieve data without html form -->
<form method="POST" enctype="multipart/form-data"> 
   {% csrf_token %} 
   {{form}}
   <input type="submit" value="new post"/>
</form>

blog/templates/post/single_post.html
<h1><a href="{% url 'blog:blog_list' %}">Welcom to our blog</a></h1>


<h3>Single_post</h3>
{{post}}
<br>
{{post.content}}
<br>
<h3>{{post.created_at}}</h3>
<br>
<img src="{{post.image.url}}" alt=""/>